version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: #For development changes to hot reload and not keep building images
      - /app/node_modules #lock node_modules dir
      - ./server:/app #load changes from server to app in image
    environment:
      - NODE_ENV=dev
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
